apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-backend
  labels:
    app: fishing-backend
spec:
  selector:
     matchLabels:
       app: fishing-backend
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: fishing-backend
    spec:
      containers:
        - image: gitar91/kluster-backend
          imagePullPolicy: Always
          name: fishing-backend
          env:
            - name: KAFKA_SERVER
              value: "fishing-kafka:9092"
            - name: FISHING_DB
              value: "postgres:5432"
---
apiVersion: v1
kind: Service
metadata:
  name: fishing-backend
  labels:
    app: fishing-backend
spec:
  ports:
    - name: fishing-backend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fishing-backend
#apiVersion: v1
#kind: Service
#metadata:
#  name: fishing-backend-lb
#spec:
#  type: LoadBalancer
#  ports:
#  - port: 80
#    protocol: TCP
#    targetPort: 8080
#  selector:
#    app: fishing-backend
