apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-frontend
  labels:
    app: fishing-frontend
spec:
  selector:
     matchLabels:
       app: fishing-frontend
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: fishing-frontend
    spec:
      containers:
        - image: gitar91/kluster-frontend
          imagePullPolicy: Always
          name: fishing-frontend
          ports:
          - containerPort: 80
          env:
            - name: PROFILE
              value: "cluster"
---
apiVersion: v1
kind: Service
metadata: 
 name: fishing-frontend-port
spec:
 type: NodePort
 selector:   
   app: fishing-frontend
 ports: 
 - name: http
   port: 80
   targetPort: 80
   nodePort: 30036
   protocol: TCP 
     
