apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-kafka
  labels:
    app: fishing-kafka
spec:
  selector:
    matchLabels:
      app: fishing-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: fishing-kafka
    spec:
      containers:
        - name: fishing-kafka
          image: wurstmeister/kafka
          imagePullPolicy: Always
          env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "$(FISHING_KAFKA_SERVICE_HOST)"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "fishing-zookeeper:2181"
          - name: KAFKA_CREATE_TOPICS
            value: "point-checking-queue:1:1:delete, point-status-queue:1:1:delete"
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: 100m
              memory: 2Gi
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: fishing-kafka
  labels:
    app: fishing-kafka
spec:
  ports:
    - name: fishing-kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: fishing-kafka

