apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-zookeeper
  labels:
    app: fishing-zookeeper
spec:
  selector:
    matchLabels:
      app: fishing-zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: fishing-zookeeper
    spec:
      containers:
        - name: fishing-zookeeper
          image: wurstmeister/zookeeper
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: 100m
              memory: 2Gi
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: fishing-zookeeper
  labels:
    app: fishing-zookeeper
spec:
  ports:
    - name: fishing-zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: fishing-zookeeper

